// Controllers
import './scripts/controllers/botController';
import './scripts/controllers/chatController';
import './scripts/controllers/messageController';
// Models
import './scripts/models/botModel';
import './scripts/models/chatModel';
import './scripts/models/messageModel';
// Views
import './scripts/views/appView';
import './scripts/views/botView';
import './scripts/views/messageView';
